- hosts: speako
  vars:
    certbot_auto_renew_user: "{{ ansible_user | default(lookup('env', 'USER')) }}"
    certbot_auto_renew_minute: "20"
    certbot_auto_renew_hour: "5"
    certbot_install_method: snap
    certbot_create_if_missing: true
    certbot_admin_email: devops@speako.app
    certbot_certs:
      - domains:
          - speako.app
    nginx_vhosts:
      - listen: 443 ssl http2
        server_name: speako.app
        root: /usr/share/nginx/html
        index: index.html index.htm
        state: present
        template: "{{ nginx_vhost_template }}"
        filename: certbot_test.conf
        extra_parameters: |
          location ~* /(api/|auth/|logout) {
              proxy_pass http://localhost:8080;
          }
          location /static/ {
              root /var/www/;
              gzip_static on;
          }
          ssl_certificate     /etc/letsencrypt/live/speako.app/fullchain.pem;
          ssl_certificate_key /etc/letsencrypt/live/speako.app/privkey.pem;
          ssl_protocols       TLSv1.1 TLSv1.2;
          ssl_ciphers         HIGH:!aNULL:!MD5;
  roles:
    - geerlingguy.certbot
    - geerlingguy.nginx
